The point of this project was to implement pseudo-code algorithms presented in the textbook Numerical Linear Algebra by Trefethan and Bau III into Python. This was done to increase my own proficiency in Python, especially for linear algebra computations.

In [8]:
#Gaussian Elimination without Pivoting
import numpy as np

A = np.array([
    [2,1,1,0],
    [4,3,3,1],
    [8,7,9,5],
    [6,7,9,8]
], dtype=float)

n = A.shape[0]

U = A.copy()
L = np.eye(n)

k = 0
while k < n-1:
    j = k + 1
    while j < n:
        L[j, k] = U[j, k] / U[k, k]
        U[j, k:] = U[j, k:] - L[j, k] * U[k, k:]
        j += 1
    k += 1

print(U)
print(L)
print(L@U)

[[2. 1. 1. 0.]
 [0. 1. 1. 1.]
 [0. 0. 2. 2.]
 [0. 0. 0. 2.]]
[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [4. 3. 1. 0.]
 [3. 4. 1. 1.]]
[[2. 1. 1. 0.]
 [4. 3. 3. 1.]
 [8. 7. 9. 5.]
 [6. 7. 9. 8.]]


In [9]:
#Cholesky Factorization
import numpy as np
import math

A = np.array([
    [2,-1,0],
    [-1,2,-1],
    [0,-1,2]
], dtype=float)

m = A.shape[0]
R = A.copy()

k = 0
while k < m:
  j = k + 1
  while j < m:
    R[j,j:] = R[j,j:] - (R[k,j]/R[k,k])*R[k,j:]
    j = j + 1
  R[k,k:] = 1/math.sqrt(R[k,k])*R[k,k:]
  k = k + 1

R = np.triu(R)
print(np.transpose(R)@R)

[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]


In [10]:
#Householder Reduction to Hessenberg Form
import numpy as np
import math

A = np.array([
    [2,-1,0],
    [-1,2,-1],
    [0,-1,2]
], dtype=float)

e_1 = np.array([[1],[0],[0]])

n = A.shape[0]

def sign(x):
    if x > 0:
        return 1
    elif x < 0:
        return -1
    else:
        return 0

k = 0
while k < n - 2:
  x = A[k+1:, k]

  e1 = np.zeros_like(x)
  e1[0] = 1.0

  v = sign(x[0])*np.linalg.norm(x)*e1 + x
  v = (1/np.linalg.norm(v))*v

  A[k+1:,k:] = A[k+1:,k:] - 2*np.outer(v,np.transpose(v)@A[k+1:,k:])
  A[1:,k+1:] = A[1:,k+1:] -2*np.outer(A[1:,k+1:]@v, np.transpose(v))
  k=k+1

print(A)

[[ 2. -1.  0.]
 [ 1.  2.  1.]
 [ 0.  1.  2.]]


In [11]:
#Rayleigh Quotient Iteration
import numpy as np
import math

eps = 1e-12

A = np.array([
    [2, -1,  0,0],
    [-1, 2, -1,8],
    [0, -1,  2,2],
    [4,5,0,9]
], dtype=float)

V = []
Lam = []
v = np.array([[1],[2],[6],[8]])
V.append(v)
lam = (np.transpose(v)@A)@v
Lam.append(lam)

k = 1
while np.linalg.norm(A@v - lam*v) >= eps:
  w = np.linalg.inv(A - Lam[k-1]*np.identity(4))@V[k-1]
  v = (1/np.linalg.norm(w))*w
  V.append(v)
  lam = (np.transpose(v)@A)@v
  Lam.append(lam)
  print(np.linalg.norm(A@v - lam*v))
  k = k + 1
print(V[k-1])
print(Lam[k-1])

5.239874646622507
2.9432068134748683
0.564364190057339
0.00112563083690431
1.2262106169667196e-08
8.95090418262362e-16
[[-0.05716626]
 [ 0.6002001 ]
 [ 0.09375499]
 [ 0.79227638]]
[[12.49920245]]


In [12]:
#Arnoldi Iteration
import numpy as np

A = np.array([
    [2, -1,  0],
    [-1, 2, -1],
    [0, -1,  2]
], dtype=float)

b = np.array([[1.0],
              [-1.0],
              [1.0]])

m = A.shape[0]

H = np.zeros((m+1, m))
Q = []

q1 = b / np.linalg.norm(b)
Q.append(q1)

n = 0

while n < m:

    v = A @ Q[n]

    for j in range(n+1):

        H[j, n] = (Q[j].T @ v)[0,0]

        v = v - H[j, n] * Q[j]

    H[n+1, n] = np.linalg.norm(v)

    if np.isclose(H[n+1,n], 0):
        break

    q_next = v / H[n+1, n]

    Q.append(q_next)

    n = n + 1

i = 0
while i < len(Q):
    print(Q[i])
    i = i +1

[[ 0.57735027]
 [-0.57735027]
 [ 0.57735027]]
[[-0.40824829]
 [-0.81649658]
 [-0.40824829]]


In [13]:
#Modified Gram-Schmidt
import numpy as np

A = np.array([
    [2, -1,  0],
    [-1, 2, -1],
    [0, -1,  2]
], dtype=float)

n = A.shape[0]

V = [A[:, i].copy() for i in range(n)]
Q = []
R = np.zeros((n, n))

for j in range(n):

    R[j, j] = np.linalg.norm(V[j])
    Q.append(V[j] / R[j, j])

    for k in range(j + 1, n):
        R[j, k] = np.dot(Q[j], V[k])
        V[k] = V[k] - R[j, k] * Q[j]

print(V)

[array([ 2., -1.,  0.]), array([ 0.6,  1.2, -1. ]), array([0.28571429, 0.57142857, 0.85714286])]
